version: '3'

services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_DB: 'thinkpro'
      POSTGRES_USER: 'thinkpro'
      POSTGRES_PASSWORD: '123456'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local
